apiVersion: v1
kind: Service
metadata:
  name: go-guestbook-frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  selector:
    app: guestbook
    tier: frontend
  ports:
  - name: http-server
    port: 8080
    targetPort: http-server
