apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - guestbook-backend.deployment.yaml
  - guestbook-backend.service.yaml
  - guestbook-frontend.deployment.yaml
  - guestbook-frontend.service.yaml
  - guestbook-mongodb.deployment.yaml
  - guestbook-mongodb.service.yaml
namespace: guestbook
commonLabels:
  app: guestbook
