resources:
  - guestbook.namespace.yaml
  - guestbook-backend.deployment.yaml
  - guestbook-backend.service.yaml
  - guestbook-frontend.deployment.yaml
  - guestbook-frontend.service.yaml
  - guestbook-mongodb.deployment.yaml
  - guestbook-mongodb.service.yaml
namespace: xymox-guestbook-main
commonLabels:
  app: guestbook
