bases:
- ../../base

resources:
- guestbook-frontend.route.yaml

patchesStrategicMerge:
- guestbook-mongodb.deployment.yaml
- guestbook-backend.deployment.yaml

# namePrefix: dev-
namespace: xymox-guestbook
commonLabels:
  environment: development

images:
- name: guestbook-backend
  newName: quay.io/xymox/guestbook
  newTag: backend-golang-latest

secretGenerator:
- name: database-secret-config
  literals:
  - dbname=guestbook
  - username=mongo
  - password=bobleponge
  - admin-username=admin
  - admin-password=jefedroi
